package tools.starcitizen.entity.product;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import tools.starcitizen.entity.StarCitizenEntity;
import tools.starcitizen.entity.product.rent.ShopRentalTemplate;

import java.util.List;

/**
 * @Author: jiawei
 * @Date: 2020/10/7
 * @Description:
 */
@Getter
@Setter
@ToString
public class ProductEntity extends StarCitizenEntity {

    private Integer size;
    private Integer grade;
    private String description;

    private String iD;
    private String name;
    private String type;
    private Double basePrice;
    private Double maxDiscountPercentage;
    private Double maxPremiumPercentage;
    private String filename;

    //物品的源属性
    private String productType;
    private String productSubType;


    private String layoutId;
    private String layoutName;
    private String shopID;
    private Double shopBasePriceOffsetPercentage;
    private Double shopMaxDiscountPercentage;
    private Double shopMaxPremiumPercentage;
    private Double shopInventory;
    private Double shopOptimalInventoryLevel;
    private String shopAutoRestock;
    private String shopAutoConsume;
    private String shopAutoGenerated;
    private Double shopMaxInventory;
    private Double shopRefreshRatePercentagePerMinute;

    private List<ShopRentalTemplate> rentals;


    private Integer canBuy = 0;
    private Integer canSell = 0;
    private Integer canRent = 0;
}
