package tools.starcitizen.entity.vo.product;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import tools.starcitizen.entity.vo.StarCitizenVO;
import tools.starcitizen.processor.excel.ExcelColumn;
import tools.starcitizen.processor.excel.ExcelPrefix;

/**
 * @Author: wftank
 * @Date: 2020/10/5
 * @Description: 组件通用实体
 */
@Getter
@Setter
@ToString(callSuper = true)
@ExcelPrefix("product")
public class ProductVO extends StarCitizenVO {

    private String iD;
    @ExcelColumn
    private String name;
    @ExcelColumn
    private String nameCn;
    @ExcelColumn
    private String type;
    @ExcelColumn
    private String typeCn;
    @ExcelColumn
    private String classDes;
    @ExcelColumn
    private String classDesCn;
    @ExcelColumn
    private Integer size;
    @ExcelColumn
    private Integer grade;
    @ExcelColumn
    private Double basePrice;
    @ExcelColumn
    private Double currentPrice;
    @ExcelColumn
    private Double minBuyingPrice;
    @ExcelColumn
    private Double maxSellingPrice;
    @ExcelColumn
    private String layoutName;
    @ExcelColumn
    private String layoutNameCn;
    @ExcelColumn
    private Double rentPrice1;
    @ExcelColumn
    private Double rentPrice3;
    @ExcelColumn
    private Double rentPrice3PerDay;
    @ExcelColumn
    private Double rentPrice7;
    @ExcelColumn
    private Double rentPrice7PerDay;
    @ExcelColumn
    private Double rentPrice30;
    @ExcelColumn
    private Double rentPrice30PerDay;
    @ExcelColumn
    private Integer commodity;
    @ExcelColumn
    private Double shopInventorySCU;
    @ExcelColumn
    private Double shopMaxInventorySCU;
    @ExcelColumn
    private Double refreshPerMinuteSCU;
    @ExcelColumn
    private Double shopInventory;
    @ExcelColumn
    private Double shopMaxInventory;
    @ExcelColumn
    private Double refreshPerMinute;
    @ExcelColumn
    private Integer canBuy;
    @ExcelColumn
    private Integer canSell;
    @ExcelColumn
    private Integer canRent;
    @ExcelColumn
    private String description;
    @ExcelColumn
    private String descriptionCn;


    @ExcelColumn
    private Double shopBasePriceOffsetPercentage;
    @ExcelColumn
    private Double maxDiscountPercentage;
    @ExcelColumn
    private Double maxPremiumPercentage;



    @ExcelColumn
    private Double shopMaxDiscountPercentage;
    @ExcelColumn
    private Double shopMaxPremiumPercentage;

    @ExcelColumn
    private Double shopOptimalInventoryLevel;
    @ExcelColumn
    private String shopAutoRestock;
    @ExcelColumn
    private String shopAutoConsume;
    @ExcelColumn
    private String shopAutoGenerated;
    @ExcelColumn
    private Double shopRefreshRatePercentagePerMinute;

    private String productType;
    private String productSubType;



}
